fixing localisation
bestpractical/rt pull request #384
Opened 2024-01-31 21:10 UTC by PPetky

This is a fix of interface missing localisation for Search/Bulk.html and 
adding localisation to lib/RT/Interface/Web/ReportsRegistry.pm

2024-02-08 20:21 UTC, sunnavy requested changes

2024-02-08 20:21 UTC, sunnavy commented on lib/RT/Interface/Web/ReportsRegistry.pm
> +    while( my($k, $v) = each %$registry ) { $v->{'title'} = loc( $v->{'title'} ); }
localising title here is kinda too early and will cause RT to save localised data to db, which is bad as users may see sticky translations even if they change the language.

Could you do the localisation later instead, e.g. in lib/RT/Interface/Web/MenuBuilder.pm and pages share/html/Prefs/DashboardsInMenu.html, share/html/Admin/Global/DashboardsInMenu.html, and share/html/Prefs/DashboardsInMenu.html?

For the latter 3 pages, I think localising the "label" item will be enough.

Other changes look good.

Thanks!

2024-02-13 23:52 UTC, PPetky commented on lib/RT/Interface/Web/ReportsRegistry.pm
> +    while( my($k, $v) = each %$registry ) { $v->{'title'} = loc( $v->{'title'} ); }
hi, I have made fixes... thnx

2024-02-20 21:45 UTC, closed without merging

2024-02-20 21:45 UTC, sunnavy commented
I tweaked and squashed the commits and merged, thanks!

One noticeable change I made is to drop the localisation of dashboard names, which are not supposed to be localised as they are generally user-defined.

-sunnavy